# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wH2jtkzqc6QrPVoT74VWR3Tsaj6GfkU9
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
from pathlib import Path
import os

# -----------------------------
# PATHS (LOCAL)
# -----------------------------
INPUT_FILE = r"datastock_data.csv"   # relative path
OUTPUT_DIR = r"output"                    # will create inside project folder

print("Current directory:", os.getcwd())
print("Input file exists:", os.path.exists(INPUT_FILE))

# -----------------------------
# LOAD DATA
# -----------------------------
df = pd.read_csv(INPUT_FILE, parse_dates=["date"])
df.sort_values(["ticker", "date"], inplace=True)
print("Data loaded")
print("Total rows:", len(df))
print("Tickers:", df["ticker"].unique())

# -----------------------------
# DAILY → MONTHLY AGGREGATION
# -----------------------------
monthly_df = (
    df.set_index("date")
      .groupby("ticker")
      .resample("ME")
      .agg(
          open=("open", "first"),
          high=("high", "max"),
          low=("low", "min"),
          close=("close", "last"),
          volume=("volume", "sum")
      )
      .reset_index()
)
print("Monthly aggregation done")

# -----------------------------
# TECHNICAL INDICATORS
# -----------------------------
def add_indicators(g):
    g = g.sort_values("date")
    g["SMA_10"] = g["close"].rolling(10).mean()
    g["SMA_20"] = g["close"].rolling(20).mean()
    g["EMA_10"] = g["close"].ewm(span=10, adjust=False).mean()
    g["EMA_20"] = g["close"].ewm(span=20, adjust=False).mean()
    return g

# -----------------------------
# WRITE OUTPUT FILES
# -----------------------------
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

for ticker in monthly_df["ticker"].unique():
    ticker_df = monthly_df[monthly_df["ticker"] == ticker].copy()
    ticker_df = add_indicators(ticker_df)

    print(f"Writing {ticker} | rows = {len(ticker_df)}")
    ticker_df.to_csv(f"{OUTPUT_DIR}/result_{ticker}.csv", index=False)

print("ALL FILES CREATED SUCCESSFULLY")
print("Output folder:", OUTPUT_DIR)

import os
os.listdir("/content/output")

import pandas as pd
import os

files = os.listdir("/content/output")
print(files)

df = pd.read_csv("/content/output/result_AAPL.csv")
print(df.shape)          # must be (24, columns)
print(df.columns)
print(df.head())

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# pandas
#

import os
os.listdir()